base_path: /Users/steve/Sites/owndsource
blurb_max: 50
date_format: '%Y-%m-%d'
home_page: index
markdown_exts:
- codehilite
- toc
- pykwiki.ext.tpl
- pykwiki.ext.post
postlist:
  max_pages: 5
  order_field: mtime
  order_type: descending
  per_page: 2
  post_type: blurb
rss_max_entries: 20
site:
  author: Steve Hutchins
  base_url: ''
  description: Articles from a tech guy
  keywords: example, pykwiki
  title: OwndSource
source_ext: .md
style: classic
theme: blogit
time_format: '%H:%M:%S'
timestamp_format: '%Y-%m-%d %H:%M'
upload_exts:
- .gif
- .jpg
- .jpeg
- .png
- .tiff
- .pdf
version: 2
web_prefix: ''
